apiVersion: apps/v1
kind: Deployment
metadata:
  name: packet-deployment
  labels:
    app: packet-app
spec:
  selector:
    matchLabels:
      app: packet-app
  replicas: 1
  template:
    metadata:
      labels:
        app: packet-app
    spec:
      containers:
        - name: packet-app
          image: shuzasa/packet-service:v1.0.0
          ports:
            - name: packet-service
              containerPort: 8080
          env:
            - name: PORT
              value: ":8080"
            - name: BOX_SERVICE_ADDRESS
              value: "porter.box"
            - name: MONGO_HOST
              value: "mongodb:27017"
            - name: APP_VERSION
              value: v1.0.0
            - name: USER_SERVICE_ADDRESS
              value: "porter.user"


---
apiVersion: v1
kind: Service
metadata:
  name: packet-service
spec:
  selector:
    app: packet-app
  ports:
    - port: 8080
      targetPort: packet-service
