// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/packet.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344942e71fec3df, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344942e71fec3df, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Item) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Packet struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Items                []*Item  `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	BoxId                string   `protobuf:"bytes,5,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344942e71fec3df, []int{2}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Packet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Packet) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Packet) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Packet) GetBoxId() string {
	if m != nil {
		return m.BoxId
	}
	return ""
}

type Response struct {
	Created              bool      `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Packet               *Packet   `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	Packets              []*Packet `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c344942e71fec3df, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetPacket() *Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *Response) GetPackets() []*Packet {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "packet.Empty")
	proto.RegisterType((*Item)(nil), "packet.Item")
	proto.RegisterType((*Packet)(nil), "packet.Packet")
	proto.RegisterType((*Response)(nil), "packet.Response")
}

func init() { proto.RegisterFile("proto/packet.proto", fileDescriptor_c344942e71fec3df) }

var fileDescriptor_c344942e71fec3df = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xed, 0x4f, 0x92, 0x7a, 0xd3, 0x16, 0xb9, 0xa0, 0x06, 0x37, 0x96, 0x59, 0x48, 0x57,
	0x2d, 0xc4, 0x47, 0x10, 0x91, 0xec, 0x64, 0x7c, 0x00, 0x69, 0x33, 0x97, 0x76, 0x90, 0x64, 0xc2,
	0xcc, 0xb4, 0xd6, 0x87, 0xf0, 0x9d, 0x25, 0xf3, 0x03, 0xfe, 0xed, 0x72, 0xce, 0xc9, 0x9d, 0xef,
	0xdc, 0x19, 0xc0, 0x4e, 0x2b, 0xab, 0xd6, 0xdd, 0xa6, 0x7e, 0x23, 0xbb, 0x72, 0x02, 0x53, 0xaf,
	0x58, 0x06, 0xc9, 0x63, 0xd3, 0xd9, 0x0f, 0xb6, 0x87, 0x71, 0x65, 0xa9, 0xc1, 0x39, 0x0c, 0xa5,
	0x28, 0x06, 0x8b, 0xc1, 0xf2, 0x9c, 0x0f, 0xa5, 0xc0, 0x5b, 0xc8, 0xeb, 0x83, 0xb1, 0xaa, 0x21,
	0xfd, 0x2a, 0x45, 0x31, 0x74, 0x01, 0x44, 0xab, 0x12, 0x78, 0x05, 0xa9, 0xd2, 0x72, 0x27, 0xdb,
	0x62, 0xe4, 0xb2, 0xa0, 0xf0, 0x1a, 0xb2, 0x83, 0xf1, 0x43, 0x63, 0x1f, 0xf4, 0xb2, 0x12, 0xec,
	0x73, 0x00, 0xe9, 0xb3, 0xa3, 0xff, 0x81, 0x2d, 0x20, 0x17, 0x64, 0x6a, 0x2d, 0x3b, 0x2b, 0x55,
	0x1b, 0x60, 0xdf, 0xad, 0x9e, 0xf6, 0x4e, 0x72, 0xb7, 0xb7, 0x8e, 0x96, 0xf0, 0xa0, 0x90, 0x41,
	0x22, 0x2d, 0x35, 0xa6, 0x18, 0x2f, 0x46, 0xcb, 0xbc, 0x9c, 0xae, 0xc2, 0xb6, 0xfd, 0x4e, 0xdc,
	0x47, 0x78, 0x09, 0xe9, 0x56, 0x9d, 0xfa, 0x42, 0x89, 0x3b, 0x38, 0xd9, 0xaa, 0x53, 0x25, 0xd8,
	0x11, 0x26, 0x9c, 0x4c, 0xa7, 0x5a, 0x43, 0x58, 0x40, 0x56, 0x6b, 0xda, 0x58, 0xf2, 0xad, 0x26,
	0x3c, 0x4a, 0xbc, 0x83, 0x70, 0x65, 0xae, 0x55, 0x5e, 0xce, 0x23, 0xc1, 0xaf, 0xc2, 0x43, 0x8a,
	0x4b, 0xc8, 0xfc, 0x97, 0x29, 0x46, 0xae, 0xca, 0xef, 0x1f, 0x63, 0x5c, 0x5a, 0x98, 0x79, 0xeb,
	0x85, 0xf4, 0x51, 0xd6, 0x84, 0x6b, 0x80, 0x27, 0xb2, 0xde, 0x33, 0x38, 0x8b, 0x73, 0xee, 0x7d,
	0x6e, 0x2e, 0xa2, 0x8c, 0x5d, 0xd9, 0x19, 0x96, 0x30, 0x7d, 0x70, 0xf5, 0xe2, 0x75, 0xfe, 0x44,
	0xfd, 0x37, 0xb3, 0x4d, 0xdd, 0xfb, 0xdf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x59, 0xbb, 0x8a,
	0x0f, 0x15, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PacketService service

type PacketServiceClient interface {
	GetPackets(ctx context.Context, in *Empty, opts ...client.CallOption) (*Response, error)
	CreatePacket(ctx context.Context, in *Packet, opts ...client.CallOption) (*Response, error)
}

type packetServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPacketServiceClient(serviceName string, c client.Client) PacketServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "packet"
	}
	return &packetServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *packetServiceClient) GetPackets(ctx context.Context, in *Empty, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PacketService.GetPackets", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packetServiceClient) CreatePacket(ctx context.Context, in *Packet, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PacketService.CreatePacket", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PacketService service

type PacketServiceHandler interface {
	GetPackets(context.Context, *Empty, *Response) error
	CreatePacket(context.Context, *Packet, *Response) error
}

func RegisterPacketServiceHandler(s server.Server, hdlr PacketServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PacketService{hdlr}, opts...))
}

type PacketService struct {
	PacketServiceHandler
}

func (h *PacketService) GetPackets(ctx context.Context, in *Empty, out *Response) error {
	return h.PacketServiceHandler.GetPackets(ctx, in, out)
}

func (h *PacketService) CreatePacket(ctx context.Context, in *Packet, out *Response) error {
	return h.PacketServiceHandler.CreatePacket(ctx, in, out)
}
